services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: kavin
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - db:/db/data/postgres
    ports:
      - "5433:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge
volumes:
  db: